export const LAUNCH_DATA_REQUESTED = "LAUNCH_DATA_REQUESTED";
export const LAUNCH_DATA_REQUEST_SUCCESS = "LAUNCH_DATA_REQUEST_SUCCESS";
export const LAUNCH_DATA_REQUEST_FAILURE = "LAUNCH_DATA_REQUEST_FAILURE";
